# Generated by Django 4.1.7 on 2023-03-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publicacoes", "0001_initial"),
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentario",
                to="publicacoes.publicacao",
            ),
        ),
    ]
