# Generated by Django 4.1.7 on 2023-03-09 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtida',
            name='created_at',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
