# Generated by Django 4.1.7 on 2023-03-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curtidas', '0002_alter_curtida_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curtida',
            old_name='created_at',
            new_name='liked_at',
        ),
    ]
